### ISSUE TITLE
doesn't compile with 4.2.1 alpha -version 8.4.0.20180118

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/tar#28]
not sure when it is planned to make the library compatible with 8.4.1
fwiw current errors are

Building library for tar-0.5.0.3..
[ 1 of 11] Compiling Codec.Archive.Tar.Index.IntTrie ( Codec/Archive/Tar/Index/IntTrie.hs, dist/build/Codec/Archive/Tar/Index/IntTrie.o )
[ 2 of 11] Compiling Codec.Archive.Tar.Index.StringTable ( Codec/Archive/Tar/Index/StringTable.hs, dist/build/Codec/Archive/Tar/Index/StringTable.o )
[ 3 of 11] Compiling Codec.Archive.Tar.Types ( Codec/Archive/Tar/Types.hs, dist/build/Codec/Archive/Tar/Types.o )

Codec/Archive/Tar/Types.hs:538:10: error:
    • No instance for (Semigroup (Entries e))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Entries e)’
    |
538 | instance Monoid (Entries e) where
    |          ^^^^^^^^^^^^^^^^^^
...

**Comment by hvr** [comment]
resolved by 3a41f95e27ef22fb63b8d15533f4d59e616867f3
